[package]
name = "many-lamps-gateway"
version.workspace = true
edition = "2021"

[dependencies]
mtrader-core = { package = "many-lamps-core", path = "../core" }
many-lamps-book = { path = "../book" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
crossbeam-channel = { workspace = true }
url = "2.4"

[dev-dependencies]
tokio-test = "0.4"
