[package]
name = "many-lamps-core"
version.workspace = true
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
crossbeam-channel = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
